// Generated by Xata Codegen 0.18.0. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "product",
    columns: [
      { name: "name", type: "string", unique: true },
      { name: "description", type: "text" },
      { name: "category", type: "link", link: { table: "product_category" } },
      { name: "image_url", type: "string", unique: true },
      { name: "price", type: "int" },
    ],
  },
  {
    name: "product_category",
    columns: [{ name: "name", type: "string", unique: true }],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL:
    "https://Stephanie-Opala-s-workspace-tp7dfp.eu-west-1.xata.sh/db/ecommerce",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
